### ISSUE TITLE
HTTP Error 414: Request-URI Too Long

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#281]
Seeing new errors after update from #280. Seen on campaign: http://campaigns-dev.hotosm.org/campaign/78a6d191ed604a15a0b605571d54dfd7. From logs, seeing two things: 

- overpass error: `HTTP Error 414: Request-URI Too Long`
- Exception on /campaign/osmcha_errors/78a6d191ed604a15a0b605571d54dfd7. Is there a reason we're still using the mapbox staging API: http://osmcha-django-staging.tilestream.net/api/v1/changesets/?

cc @dimasciput 

```
http://osmcha-django-staging.tilestream.net/api/v1/changesets/?page=1&page_size=15&geometry=%7B%22type%22%3A+%22MultiPolygon%22%2C+%22coordinates%22%3A+%5B%5B%5B%5B28.947300910949707%2C+41.01003798172351%5D%2C+%5B28.94747257232666%2C+41.01065326892827%5D%2C+%5B28.946914672851562%2C+41.0108475689571%5D%2C+%5B28.946807384490967%2C+41.0107180356682%5D%2C+%5B28.94597053527832%2C+41.01102567681349%5D%2C+%5B28.946228027343754%2C+41.01183525191069%5D%2C+%5B28.945090770721436%2C+41.01209431384083%5D%2C+%5B28.945026397705075%2C+41.011964783003094%5D%2C+%5B28.94391059875488%2C+41.01209431384083%5D%2C+%5B28.94436120986938%2C+41.01279053773046%5D%2C+%5B28.943781852722168%2C+41.01300102257428%5D%2C+%5B28.943824768066406%2C+41.01313055137465%5D%2C+%5B28.943181037902832%2C+41.01345437226147%5D%2C+%5B28.9433741569519%2C+41.01372961876382%5D%2C+%5B28.942623138427734%2C+41.01405343670605%5D%2C+%5B28.940970897674564%2C+41.01181906050625%5D%2C+%5B28.943717479705807%2C+41.01096091037594%5D%2C+%5B28.946592807769775%2C+41.01019989996603%5D%2C+%5B28.947300910949707%2C+41.01003798172351%5D%5D%5D%2C+%5B%5B%5B28.947494029998776%2C+41.010637077233326%5D%2C+%5B28.947901725769043%2C+41.011932400253876%5D%2C+%5B28.9433741569519%2C+41.015024880982644%5D%2C+%5B28.942623138427734%2C+41.014069627561376%5D%2C+%5B28.94341707229614%2C+41.01374580969873%5D%2C+%5B28.943202495574948%2C+41.01348675426262%5D%2C+%5B28.943824768066406%2C+41.01317912460917%5D%2C+%5B28.943760395050052%2C+41.012984831456315%5D%2C+%5B28.9443826675415%2C+41.01283911121565%5D%2C+%5B28.94388914108276%2C+41.01209431384083%5D%2C+%5B28.94500494003296%2C+41.01198097437174%5D%2C+%5B28.945090770721436%2C+41.01207812250005%5D%2C+%5B28.946228027343754%2C+41.01188382610021%5D%2C+%5B28.9459490776062%2C+41.01102567681349%5D%2C+%5B28.946807384490967%2C+41.01070184398918%5D%2C+%5B28.94697904586792%2C+41.0108475689571%5D%2C+%5B28.947494029998776%2C+41.010637077233326%5D%5D%5D%2C+%5B%5B%5B28.947279453277588%2C+41.01003798172351%5D%2C+%5B28.940949440002438%2C+41.01181906050625%5D%2C+%5B28.94060611724853%2C+41.011122826350395%5D%2C+%5B28.9420223236084%2C+41.0106856523062%5D%2C+%5B28.943760395050052%2C+41.01024847536121%5D%2C+%5B28.94567012786865%2C+41.00982748741331%5D%2C+%5B28.9469575881958%2C+41.009697952118955%5D%2C+%5B28.947279453277588%2C+41.01003798172351%5D%5D%5D%5D%7D&date__gte=2017-08-10&date__lte=2017-08-10
http://osmcha-django-staging.tilestream.net/api/v1/changesets/?page=1&page_size=15&geometry=%7B%22type%22%3A+%22MultiPolygon%22%2C+%22coordinates%22%3A+%5B%5B%5B%5B39.20477628707886%2C+-6.757458043732384%5D%2C+%5B39.20496940612793%2C+-6.757809635650875%5D%2C+%5B39.204561710357666%2C+-6.759173383703515%5D%2C+%5B39.20495867729187%2C+-6.759429086035117%5D%2C+%5B39.20507669448852%2C+-6.75982329353133%5D%2C+%5B39.20489430427551%2C+-6.761005914091012%5D%2C+%5B39.205065965652466%2C+-6.7615279708948695%5D%2C+%5B39.211578369140625%2C+-6.762337690536159%5D%2C+%5B39.215312004089355%2C+-6.7633391840049315%5D%2C+%5B39.215312004089355%2C+-6.760078995519152%5D%2C+%5B39.21348810195923%2C+-6.759269272093714%5D%2C+%5B39.21247959136962%2C+-6.758715250021159%5D%2C+%5B39.21172857284546%2C+-6.758587398683481%5D%2C+%5B39.20889616012573%2C+-6.756989254110036%5D%2C+%5B39.20679330825806%2C+-6.756456538078499%5D%2C+%5B39.20554876327515%2C+-6.756946636849115%5D%2C+%5B39.20477628707886%2C+-6.757458043732384%5D%5D%5D%2C+%5B%5B%5B39.205063283443465%2C+-6.761525307341209%5D%2C+%5B39.204360544681556%2C+-6.761546615770315%5D%2C+%5B39.202890694141395%2C+-6.762026055176944%5D%2C+%5B39.20245081186296%2C+-6.762580073454399%5D%2C+%5B39.204403460025794%2C+-6.764369974316756%5D%2C+%5B39.20726805925371%2C+-6.769036470374615%5D%2C+%5B39.21001464128496%2C+-6.770506726911653%5D%2C+%5B39.2131903767586%2C+-6.772658833475918%5D%2C+%5B39.21348810195923%2C+-6.771979642465646%5D%2C+%5B39.21360611915589%2C+-6.77144694296508%5D%2C+%5B39.21374559402466%2C+-6.770296310036945%5D%2C+%5B39.21424180269243%2C+-6.7678858317001716%5D%2C+%5B39.21434909105303%2C+-6.767353127681462%5D%2C+%5B39.21466022729875%2C+-6.767353127681462%5D%2C+%5B39.21596914529802%2C+-6.767768636866486%5D%2C+%5B39.21636343002319%2C+-6.7665087906077614%5D%2C+%5B39.21664237976074%2C+-6.765725713264059%5D%2C+%5B39.21698838472368%2C+-6.764849410921634%5D%2C+%5B39.21709030866623%2C+-6.764369974316742%5D%2C+%5B39.2170098423958%2C+-6.764103620441757%5D%2C+%5B39.21690791845323%2C+-6.763874555991797%5D%2C+%5B39.216687977314%2C+-6.763624183096687%5D%2C+%5B39.216454625129714%2C+-6.763530959113211%5D%2C+%5B39.21604424715043%2C+-6.763485678886166%5D%2C+%5B39.21559900045396%2C+-6.763427080939024%5D%2C+%5B39.215293228626265%2C+-6.763320539198695%5D%2C+%5B39.21143084764481%2C+-6.762292410197299%5D%2C+%5B39.205063283443465%2C+-6.761525307341209%5D%5D%5D%2C+%5B%5B%5B39.21597719192505%2C+-6.767771300385733%5D%2C+%5B39.21691060066223%2C+-6.768186809210883%5D%2C+%5B39.21839118003845%2C+-6.7692948309962375%5D%2C+%5B39.21895980834961%2C+-6.768666242026297%5D%2C+%5B39.219555258750916%2C+-6.768549047382058%5D%2C+%5B39.219850301742554%2C+-6.768341293170061%5D%2C+%5B39.220134615898125%2C+-6.768325312073129%5D%2C+%5B39.22039747238159%2C+-6.7682400795472235%5D%2C+%5B39.22066569328308%2C+-6.768058960379698%5D%2C+%5B39.220837354660034%2C+-6.767755319269933%5D%2C+%5B39.22092318534851%2C+-6.7672013069284755%5D%2C+%5B39.22089636325836%2C+-6.766924300519364%5D%2C+%5B39.22100901603699%2C+-6.766583369336161%5D%2C+%5B39.2212826013565%2C+-6.766444865974238%5D%2C+%5B39.221309423446655%2C+-6.766119915623001%5D%2C+%5B39.221588373184204%2C+-6.7659068333067705%5D%2C+%5B39.222092628479004%2C+-6.7649799241372275%5D%2C+%5B39.220343828201294%2C+-6.764436562762544%5D%2C+%5B39.2182731628418%2C+-6.763978434069766%5D%2C+%5B39.217296838760376%2C+-6.763722734145335%5D%2C+%5B39.21688914299011%2C+-6.763850584124471%5D%2C+%5B39.21700716018677%2C+-6.764127592296513%5D%2C+%5B39.217087626457214%2C+-6.764372637854755%5D%2C+%5B39.21700179576873%2C+-6.7648520744569876%5D%2C+%5B39.21663701534271%2C+-6.765725713264059%5D%2C+%5B39.21636879444122%2C+-6.76649813650276%5D%2C+%5B39.21597719192505%2C+-6.767771300385733%5D%5D%5D%2C+%5B%5B%5B39.21375632286072%2C+-6.7703389261202345%5D%2C+%5B39.213584661483765%2C+-6.771489558946757%5D%2C+%5B39.21349883079529%2C+-6.772032912383361%5D%2C+%5B39.213144779205315%2C+-6.772714766810608%5D%2C+%5B39.21251177787783%2C+-6.773599045335696%5D%2C+%5B39.212576150894186%2C+-6.774035857021005%5D%2C+%5B39.21285510063174%2C+-6.77412108852323%5D%2C+%5B39.21323060989382%2C+-6.774046510959613%5D%2C+%5B39.21378850936892%2C+-6.773769508479466%5D%2C+%5B39.214121103286764%2C+-6.773684276915106%5D%2C+%5B39.21503305435183%2C+-6.7736310071797385%5D%2C+%5B39.21564459800723%2C+-6.773460543987%5D%2C+%5B39.21801567077638%2C+-6.772544303294152%5D%2C+%5B39.21776890754702%2C+-6.772096836276834%5D%2C+%5B39.21761870384219%2C+-6.771542828918606%5D%2C+%5B39.21761870384219%2C+-6.771244517000684%5D%2C+%5B39.2187559604645%2C+-6.769603798155967%5D%2C+%5B39.21840727329254%2C+-6.769305485039511%5D%2C+%5B39.21695351600647%2C+-6.768208117346119%5D%2C+%5B39.21597182750702%2C+-6.767755319269933%5D%2C+%5B39.21466290950775%2C+-6.76736111824606%5D%2C+%5B39.214335680007935%2C+-6.7673664452890705%5D%2C+%5B39.21375632286072%2C+-6.7703389261202345%5D%5D%5D%5D%7D&date__gte=2017-08-11&date__lte=2017-08-16
[2017-08-13 22:05:30,940] ERROR in app: Exception on /campaign/osmcha_errors/78a6d191ed604a15a0b605571d54dfd7 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/web/osm_reporter/campaign_manager/views.py", line 113, in get_osmcha_errors_function
    additional_data=clean_argument(request.args)
  File "/home/web/osm_reporter/campaign_manager/models/campaign.py", line 201, in render_insights_function
    'widget': selected_function.get_ui_html()
  File "/home/web/osm_reporter/campaign_manager/insights_functions/_abstract_insights_function.py", line 175, in get_ui_html
    return self._get_html('ui', self.get_ui_html_file())
  File "/home/web/osm_reporter/campaign_manager/insights_functions/_abstract_insights_function.py", line 151, in _get_html
    self.run()
  File "/home/web/osm_reporter/campaign_manager/insights_functions/_abstract_insights_function.py", line 65, in run
    self._function_raw_data = self.get_data_from_provider()
  File "/home/web/osm_reporter/campaign_manager/insights_functions/osmcha_changesets.py", line 63, in get_data_from_provider
    start_date=start_date, end_date=end_date)
  File "/home/web/osm_reporter/campaign_manager/data_providers/_abstract_osmcha_provider.py", line 60, in get_data
    data = request.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error with Overpass
Traceback (most recent call last):
  File "/home/web/osm_reporter/reporter/osm.py", line 208, in fetch_osm
    url_handle = urlopen(web_request, timeout=60)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 414: Request-URI Too Long
```

**Comment by dimasciput** [comment]
> @smit1678 Is there a reason we're still using the mapbox staging API: 

I think we just haven't change it yet, which server should we use?

**Comment by dimasciput** [comment]
This error is because we are using geometry for a request to osmcha, that's why when the polygon gets complicated the request will gets longer.

@meomancer can you confirm this?

**Comment by cchristelis** [comment]
Let's check geometry complexity. If it will cause this error, let's use a simplified version of the geometry in the query.

**Comment by smit1678** [comment]
It looks like we're just sending the raw geojson data of the AOI shapes. This will only get more complex when we have more areas being tracked. It seems like we should be sending the union of the areas, plus a little simplification.

**Comment by meomancer** [comment]
hi @smit1678 @cchristelis 
we don't use raw geojson, instead we use one feature
as per disscussion in here : https://github.com/hotosm/field-campaigner/pull/104#issuecomment-307716697
The error is ocurred because we use GET and the coordinates of polygon is complex.

**Comment by cchristelis** [comment]
@meomancer, let's reduce the complexity of that one feature, by simplifying it.

**Comment by dimasciput** [comment]
> It looks like we're just sending the raw geojson data of the AOI shapes. This will only get more complex when we have more areas being tracked. It seems like we should be sending the union of the areas, plus a little simplification.

I updated to use union of area, one thing left to do is simplification. We can use this method http://toblerity.org/shapely/manual.html#object.simplify

**Comment by smit1678** [comment]
@dimasciput I rebuilt and redeployed the latest updates but still seeing this error on http://campaigns-dev.hotosm.org/campaign/78a6d191ed604a15a0b605571d54dfd7. 

```
Error with Overpass
Traceback (most recent call last):
  File "/home/web/osm_reporter/reporter/osm.py", line 208, in fetch_osm
    url_handle = urlopen(web_request, timeout=60)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 414: Request-URI Too Long
```
