### ISSUE TITLE
Error in app: Exception on /campaign/osmcha_errors_data/

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#421]
```
osmreporter_web | [2018-04-03 10:17:05,123] ERROR in app: Exception on /campaign/osmcha_errors_data/221042831bbf445ca9038a2553f2431b [GET]
osmreporter_web | Traceback (most recent call last):
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
osmreporter_web |     response = self.full_dispatch_request()
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
osmreporter_web |     rv = self.handle_user_exception(e)
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
osmreporter_web |     return original_handler(e)
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
osmreporter_web |     reraise(exc_type, exc_value, tb)
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
osmreporter_web |     raise value
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
osmreporter_web |     rv = self.dispatch_request()
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
osmreporter_web |     return self.view_functions[rule.endpoint](**req.view_args)
osmreporter_web |   File "/home/web/osm_reporter/campaign_manager/views.py", line 156, in get_osmcha_errors_data
osmreporter_web |     osmcha_changeset.run()
osmreporter_web |   File "/home/web/osm_reporter/campaign_manager/insights_functions/_abstract_insights_function.py", line 65, in run
osmreporter_web |     self._function_raw_data = self.get_data_from_provider()
osmreporter_web |   File "/home/web/osm_reporter/campaign_manager/insights_functions/osmcha_changesets.py", line 69, in get_data_from_provider
osmreporter_web |     max_page=self.max_page)
osmreporter_web |   File "/home/web/osm_reporter/campaign_manager/data_providers/_abstract_osmcha_provider.py", line 70, in get_data
osmreporter_web |     data = request.json()
osmreporter_web |   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
osmreporter_web |     return complexjson.loads(self.text, **kwargs)
osmreporter_web |   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
osmreporter_web |     return _default_decoder.decode(s)
osmreporter_web |   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
osmreporter_web |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
osmreporter_web |   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
osmreporter_web |     raise JSONDecodeError("Expecting value", s, err.value) from None
osmreporter_web | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Dragneel7** [comment]
@smit1678 Can you please tell how to reproduce this error.
